function execute() {    
    return Response.success([
  { title: "Action", input: "/the-loai/action" ,script: "gen2.js" },
  { title: "Adventure", input: "/the-loai/adventure" ,script: "gen2.js" },
  { title: "Fantasy", input: "/the-loai/fantasy" ,script: "gen2.js" },
  { title: "Manhua", input: "/the-loai/manhua" ,script: "gen2.js" },
  { title: "Chuyển Sinh", input: "/the-loai/chuyen-sinh" ,script: "gen2.js" },
  { title: "Truyện Màu", input: "/the-loai/truyen-mau" ,script: "gen2.js" },
  { title: "Xuyên Không", input: "/the-loai/xuyen-khong" ,script: "gen2.js" },
  { title: "Manhwa", input: "/the-loai/manhwa" ,script: "gen2.js" },
  { title: "Drama", input: "/the-loai/drama" ,script: "gen2.js" },
  { title: "Historical", input: "/the-loai/historical" ,script: "gen2.js" },
  { title: "Manga", input: "/the-loai/manga" ,script: "gen2.js" },
  { title: "Seinen", input: "/the-loai/seinen" ,script: "gen2.js" },
  { title: "Comedy", input: "/the-loai/comedy" ,script: "gen2.js" },
  { title: "Martial Arts", input: "/the-loai/martial-arts" ,script: "gen2.js" },
  { title: "Mystery", input: "/the-loai/mystery" ,script: "gen2.js" },
  { title: "Romance", input: "/the-loai/romance" ,script: "gen2.js" },
  { title: "Shounen", input: "/the-loai/shounen" ,script: "gen2.js" },
  { title: "Sports", input: "/the-loai/sports" ,script: "gen2.js" },
  { title: "Supernatural", input: "/the-loai/supernatural" ,script: "gen2.js" },
  { title: "Harem", input: "/the-loai/harem" ,script: "gen2.js" },
  { title: "Webtoon", input: "/the-loai/webtoon" ,script: "gen2.js" },
  { title: "School Life", input: "/the-loai/school-life" ,script: "gen2.js" },
  { title: "Psychological", input: "/the-loai/psychological" ,script: "gen2.js" },
  { title: "Cổ Đại", input: "/the-loai/co-dai" ,script: "gen2.js" },
  { title: "Ecchi", input: "/the-loai/ecchi" ,script: "gen2.js" },
  { title: "Gender Bender", input: "/the-loai/gender-bender" ,script: "gen2.js" },
  { title: "Shoujo", input: "/the-loai/shoujo" ,script: "gen2.js" },
  { title: "Slice of Life", input: "/the-loai/slice-of-life" ,script: "gen2.js" },
  { title: "Ngôn Tình", input: "/the-loai/ngon-tinh" ,script: "gen2.js" },
  { title: "Horror", input: "/the-loai/horror" ,script: "gen2.js" },
  { title: "Sci-fi", input: "/the-loai/sci-fi" ,script: "gen2.js" },
  { title: "Tragedy", input: "/the-loai/tragedy" ,script: "gen2.js" },
  { title: "Mecha", input: "/the-loai/mecha" ,script: "gen2.js" },
  { title: "Comic", input: "/the-loai/comic" ,script: "gen2.js" },
  { title: "One shot", input: "/the-loai/one-shot" ,script: "gen2.js" },
  { title: "Shoujo Ai", input: "/the-loai/shoujo-ai" ,script: "gen2.js" },
  { title: "Anime", input: "/the-loai/anime" ,script: "gen2.js" },
  { title: "Josei", input: "/the-loai/josei" ,script: "gen2.js" },
  { title: "Smut", input: "/the-loai/smut" ,script: "gen2.js" },
  { title: "Shounen Ai", input: "/the-loai/shounen-ai" ,script: "gen2.js" },
  { title: "Mature", input: "/the-loai/mature" ,script: "gen2.js" },
  { title: "Soft Yuri", input: "/the-loai/soft-yuri" ,script: "gen2.js" },
  { title: "Adult", input: "/the-loai/adult" ,script: "gen2.js" },
  { title: "Doujinshi", input: "/the-loai/doujinshi" ,script: "gen2.js" },
  { title: "Live action", input: "/the-loai/live-action" ,script: "gen2.js" }
]);
}
